### ISSUE TITLE
About the get_super

### ISSUE THREAD

**Issue by zhanghaiyang9999** [elastio/elastio-snap#103]
Hi, 
I saw the function elastio_snap_get_super to get the get_super address and the GET_SUPER_ADDR is  the address of the get_super got from sysmap, but I have a question, why here need to plus the address of kfree and minus the KFREE_ADDR of  the address kfree? are they different between address of kfree and KFREE_ADDR? please see the following code.

struct super_block* (*elastio_snap_get_super)(struct block_device *) = (GET_SUPER_ADDR != 0) ?
	(struct super_block* (*)(struct block_device*)) (GET_SUPER_ADDR + (long long)(((void *)kfree) - (void *)KFREE_ADDR)) : NULL;

Thanks!

**Comment by nickchen-cpu** [comment]
Address Space Layout Randomization?

**Comment by e-kov** [comment]
@nickchen-cpu you are right. That's the logic. `KFREE_ADDR` is an address of the `kfree` function at the moment of the kernel module compilation taken from the `/boot/System.map-$(uname -r)`. And calculated delta between `kfree` and `KFREE_ADDR` is applicable for other functions. `printk` became a macro starting from 5.15. Thus we are started to use another function as an anchor.

**Comment by anelson** [comment]
@e-kov this appears to be addressed; can we close?

**Comment by e-kov** [comment]
Yes, @zhanghaiyang9999 asked a question which is responded.
