### ISSUE TITLE
tracing_mrf should match fops to find orig_mrf in case queue doesn’t match it

### ISSUE THREAD

**Issue by nickchen-cpu** [elastio/elastio-snap#119]
Hi

1. elastio-snap modifies ```bd_disk->fops->submit_bio```, so please see the following statements(3 and 4).

2. ``` tracer_queue_matches_bio ``` in ```tracing_mrf``` was used to identify the ```bio```'s corresponding ```queue```(and ```orig_mrf```) but this only worked for old style ```queue->make_request``` rather than new style ```fops->submit_bio```(The explanation is at the end of this article).

3. So ```tracing_mrf``` should match `fops` to find `orig_mrf` in case `tracer_queue_matches_bio` doesn’t match(kernel5.9+).

4. In ```__tracer_should_reset_mrf``` we also need to handle fops correctly.

Code:
```c
static int __tracer_should_reset_mrf(const struct snap_device *dev){
	int i;
	struct snap_device *cur_dev;
	struct request_queue *q = bdev_get_queue(dev->sd_base_dev);

	if(elastio_snap_get_bd_mrf(dev->sd_base_dev) != tracing_mrf) return 0;
	if(dev != snap_devices[dev->sd_minor]) return 0;

	//return 0 if there is another device tracing the same queue as dev.
	if(snap_devices){
		tracer_for_each(cur_dev, i){
			if(!cur_dev || test_bit(UNVERIFIED, &cur_dev->sd_state) || cur_dev == dev) continue;
Here***********if(q == bdev_get_queue(cur_dev->sd_base_dev)) return 0;
		}
	}

	return 1;
}
```
Please take into account the followings(Kernel 5.9+):

1. The SCSI block device's ```sd_fops``` has no ```sumbit_bio``` , instead it only has fallback ```blk_mq_submit_bio``` which is global export function, once ```sd_fops``` is modified in one of the SCSI block device, all of the SCSI block devices' ```sd_fops``` will be modified too, **not only that in the same queue（gendisk).**

2. The md block device's fops(```md_fops```) was shared among all of the md block devices, once it's modified, all of the md block devices' fops will be modified.
3. The dm block device's fops(``` dm_blk_dops```) was shared among all of the dm block devices, once it's modified, all of the dm block devices' fops will be modified.

We should match ```fops``` instead of ```bdev_get_queue``` .

New style kernel(5.9+)'s ```submit_bio``` :
```
1. sda1
       \
2. sda2 ->fops(sd_fops)->submit_bio (NULL and fallback to blk_mq_submit_bio)
       /
3. sdb1

4. dm-0
        \
         ->fops(dm_blk_dops)->submit_bio (dm_submit_bio)
        /
5. dm-1
```
Old style kernel(5.8-)'s ```mrf``` :
```
1. sda1
       \
        ->sda_queue->make_request
       /
2. sda2
    
3. sdb1->sdb_queue->make_request

4. dm0->dm0_queue->make_request
    
5. dm1->dm1_queue->make_request
```
Hope the above diagrams are clear.

If my statement is ambiguous, I will try to clear it.

**1. `make_request` is in the scope of queue(gendisk)**
**2. `submit_bio` is in the scope of disk type(md/dm/scsi).**

Best Regards,
Nick

**Comment by nickchen-cpu** [comment]
If fixing this, we can fix https://github.com/elastio/elastio-snap/issues/89.

**Comment by e-kov** [comment]
@nickchen-cpu thanks a lot for the detailed investigation of the problem. This will be helpful for the implementation of the fix.

**Comment by nickchen-cpu** [comment]
Update the ```tracing_mrf```'s function issue:


Suppose the system are running 2 device mapper devices called ```dm-0```, ```dm-1```,
and we setup-snapshot for only```dm-0```, as mentioned earlier,
```dm-1(gendisk)->fops->submit_bio``` will also be changed to ```tracing_mrf```.

Here comes the problem:
bio for dm-1 will not be able to find orig_mrf because **tracer_queue_matches_bio is not true**
so it will go to the following **if else result**:
```c
	} else if (elastio_snap_bio_bi_disk(bio)->fops->submit_bio) {
		if (elastio_snap_bio_bi_disk(bio)->fops->submit_bio == tracing_mrf) {
          Here>>>>>MRF_SET_RETURN_VALUE(elastio_snap_null_mrf(bio))<<<<<Here
```

But that's a problem, the original ```dm1(gendisk)->fops->submit_bio``` is not ```elastio_snap_null_mrf```(which call ```blk_mq_submit_bio ```), but in fact it should call ```dm_submit_bio``` instead.

So we need to find some method to get ```dm-1```'s correct ```original_mrf```






```c
	tracer_for_each(dev, i){
		// traced but unverfied, still do bio
		if(!dev || (!test_bit(TRACED, &dev->sd_state) && test_bit(UNVERIFIED, &dev->sd_state)) || !tracer_queue_matches_bio(dev, bio)) continue;

		orig_mrf = dev->sd_orig_mrf;

		if(tracer_should_trace_bio(dev, bio)){
			if (should_ignore_tracing(bio) || is_lowlevel_io_bio(dev, bio)) goto call_orig;

			if(test_bit(SNAPSHOT, &dev->sd_state)) ret = snap_trace_bio(dev, bio);
			else ret = inc_trace_bio(dev, bio);
			goto out;
		}

		goto call_orig;
	}

	// do fops match to find original mrf for the whole gen disk, we need original mrf for this bio to work
	tracer_for_each(dev, i){
		// traced but unverfied, still do bio
		if(!dev || (!test_bit(TRACED, &dev->sd_state) && test_bit(UNVERIFIED, &dev->sd_state)) || !tracer_fops_matches_bio(dev, bio)) continue;

		orig_mrf = dev->sd_orig_mrf;

		goto call_orig;
	}
```
