### ISSUE TITLE
Driver occasionally fails qcow2 CI tests

### ISSUE THREAD

**Issue by skypodolsky** [elastio/elastio-snap#127]
Sometimes, especially on arm64 builders, the following qcow2 issue is observed. This needs to be addressed.

![image (5)](https://user-images.githubusercontent.com/5726567/170754195-495a71ad-f51a-4c3e-9f92-ce44267c34ca.png)

**Comment by anelson** [comment]
This is important because it might be a sign of a bug in the driver that customers may encounter.  Because of that risk we need to get to the bottom of it.

**Comment by skypodolsky** [comment]
Fixed in #132
