### ISSUE TITLE
test_track_writes randomly fails

### ISSUE THREAD

**Issue by skypodolsky** [elastio/elastio-snap#167]
###### Details:

Subtask of #166 

This is a very rare event, was seen only once on debian10 (amd64), LVM + qcow2 disk

```
======================================================================
FAIL: test_track_writes (test_snapshot.TestSnapshot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/test_snapshot.py", line 74, in test_track_writes
    self.assertGreater(end_nr, start_nr)
AssertionError: 4 not greater than 4
```

**Comment by e-kov** [comment]
The same failure has been observed w/o LVM but on qcow2 too, this time it's on
Arch: arm64
Distributive: CentOS 8
Kernel: 4.18.0-408.el8.aarch64
Filesystem: ext2 (no LVM)
Device type: qcow2
https://github.com/elastio/elastio-snap/actions/runs/3480673604/jobs/5820780037#step:22:69
