### ISSUE TITLE
Behavior reading snapshot when snapshot is in error state

### ISSUE THREAD

**Issue by kevinhoffman** [elastio/elastio-snap#185]
Hi! First as an intro, at Axcient we're provide image-based backups to our turn-key cloud, focused on the MSP/SMB market, with about 3200 MSP partners. Today we only backup Windows machines (relying on Microsoft VSS for snapshots of block devices). We've been working on image-based backups for Linux, originally we used the dattobd kernel module, but we switched to this fork as we found it is higher quality and more actively maintained.

We are in a different part of the market than elastio (not competitors) and we'd like to collaborate on the elastio-snap kernel module, and contribute any bugfixes/enhancements back to this kernel module (rather than forking and having our own variant). I also know Naj & @anelson from AppAssure :) We believe it would be very good for Linux to have an open source snapshot driver that is equivalent to Microsoft VSS on Windows. This seems to be the highest quality open source kernel module out there today and so we want to contribute, it will benefit us all and the community. We're doing a lot of stress testing on the kernel module and likely will have some more fixes to contribute over time.

Recently a team member @kgermanov contributed #179 to expose more error state information in `/proc`. 

In PR #132 the dattobd behavior was changed where if the snapshot was in a failed state (e.g., COW file reached max size or ran out of disk space, out of memory, etc.), that instead of failing the reads from the snapshot, it would provide zeros instead. For us this is a concern, as we don't want backups to send data that is invalid because the snapshot has failed. While we could check the error state before every read, that is slow and also doesn't guarantee that it didn't fail right after we checked the state and before the read.

We wanted to discuss what you would think of some kind of compile-time or kernel module parameter that would reverse the behavior, and have reads to the snapshot block device fail immediately if the snapshot was in a failed state. In this way the backup could fail immediately if the snapshot device fails, and the backup would not have read/stored any bad blocks in that case. What do you think?

**Comment by anelson** [comment]
Hi @kevinhoffman, great to see you here!  We were happy to see a contribution from @kgermanov and we're definitely open to further collaboration.

Yeah, that change felt pretty dirty at the time, the problem is that the failure mode when using the `elastio` CLI if the COW file is too big or there's no space was awful from a customer perspective.  `elastio` knows about this very odd way of reporting errors, and it lets us handle the errors the right way in userland.  I completely understand that this not a solution that generalizes to other callers though.  I think what you're proposing is quite reasonable, and I think we'd be open to a PR to implement it.  In that case I think the more sane failure handling logic should be the default, and the elastio-specific logic would be something that has to be enabled explicitly.

The primary maintainers of `elastio-snap` are @e-kov  and @skypodolsky so I'll defer to them on what form they think this should take.  Given the peculiarities of DKMS I assume they'll suggest to make it a runtime setting, but I'll let them speak for themselves.  Guys, what do you think?

**Comment by e-kov** [comment]
Hi @kevinhoffman and @anelson,

Adam is right. We are using a snapshot device as a memory-mapped file. And the previous behavior leads to the `SIGBUS` signal when the snapshot device has gone away due to an error. We were aware of potential issues for elastio-snap users, if any. And we were planning a change in the API with addition of an arg like `bool allow_mem_mapping` into the `elastio_snap_setup_snapshot` function in the `libelastio-snap.so`  https://github.com/elastio/elastio-snap/blob/f7c23305e4db788423457c60da4b77843eb4785f/lib/libelastio-snap.h#L17
And to add the same as an optional argument to the `eioctl`.
So anyone who needs to use the previous behavior would use it with `allow_mem_mapping = false` or without of an arg for the setup snapshot command. And we, or anyone using snapshot memory mapping, would simply explicitly set this parameter to `true`. That was the plan. But it was not done due to lack of ~time~ demand. =)

I'll be glad to implement this functionality and make our driver more versatile in use.

**Comment by kevinhoffman** [comment]
@anelson - good to hear from you! 

hi @e-kov - that would make sense and much appreciated if that flag were added and allowed either behavior. Maybe the flag should just name the behavior explicitly, e.g., `propagate_snapshot_io_errors` or something, as some other users of the application might actually memory map the snapshot but prefer to still immediately understand if the snapshot device failed (i.e. catch SIGBUS signal and then check the snapshot error state using `/proc/...` file or an ioctl, and if so then consider the signal an indication that the snapshot failed, etc.). We're not doing memory mapped IO in our case, but I could imagine that other users of the driver might do mmap'd IO but also still might want to immediately fail their reads rather than starting to read zeros at an unknown time of snapshot failure, etc.

You might know how you prefer to implement this, let us know if you'd like us to give a try at a PR and we could also attempt it. Thanks!

**Comment by kevinhoffman** [comment]
@e-kov FYI, we've discussed internally and @kgermanov will be submitting a PR along the direction described above.

**Comment by e-kov** [comment]
> @e-kov FYI, we've discussed internally and @kgermanov will be submitting a PR along the direction described above.

@kevinhoffman @kgermanov thanks for offering help and I'm sorry for the delay in reply. I'm going to roll out a PR for review in a day or two. The work is already in progress. In addition to the change under discussion, I'd like to improve some memory-mapped snap dev use cases and make error handling a bit simpler in general.

**Comment by kgermanov** [comment]
@e-kov  Looks like we should not create separate option.

Key line of PR #132 was this line(https://github.com/elastio/elastio-snap/pull/132/files#diff-3d1684da11d36e060b94eb1385661e3c5d38497cfaf23118df4199f410ba3593R3281):
```
- if (!bio_needs_cow(bio, dev) || memory_is_too_low(dev)) {
+ if (!bio_needs_cow(bio, dev) || memory_is_too_low(dev) || tracer_read_cow_fail_state(dev)) {
```

It stops tracking if cow file in fail state. And this helps for SIGBUS error.

But we need stop tracking on fail state too.

**Comment by kgermanov** [comment]
I retested this case (read after fail) for branch before PR #132:

```
root@user-vm:/home/kgermanov# (sleep 1 && dd if=/dev/urandom of=/tmp/fs/big_file count=100 bs=1M && date)&  dd if=/dev/elastio-snap0 of=/dev/null status=progress && date || date
[1] 313123
153334272 bytes (153 MB, 146 MiB) copied, 5 s, 28.0 MB/s100+0 records in
100+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 5.39002 s, 19.5 MB/s
Wed 09 Nov 2022 08:33:15 PM +04
889041408 bytes (889 MB, 848 MiB) copied, 44 s, 20.2 MB/s
dd: error reading '/dev/elastio-snap0': Input/output error
1765088+0 records in
1765088+0 records out
903725056 bytes (904 MB, 862 MiB) copied, 44.383 s, 20.4 MB/s
[1]+  Done                    ( sleep 1 && dd if=/dev/urandom of=/tmp/fs/big_file count=100 bs=1M && date )
Wed 09 Nov 2022 08:33:53 PM +04

root@user-vm:/home/kgermanov# dmesg -T -c
[Wed Nov  9 20:33:14 2022] elastio-snap: cow file '/tmp/fs/.eliosnap' max size exceeded (10485760/10485760): -27
[Wed Nov  9 20:33:14 2022] elastio-snap: error writing cow data: -27
[Wed Nov  9 20:33:14 2022] elastio-snap: error writing cow data and mapping: -27
[Wed Nov  9 20:33:14 2022] elastio-snap: error handling write bio: -27
[Wed Nov  9 20:33:14 2022] elastio-snap: error handling write bio in kernel thread: -27
[Wed Nov  9 20:33:52 2022] elastio-snap: invalid file 'read' size: 10485760, 4096, 0: -5
[Wed Nov  9 20:33:52 2022] elastio-snap: error reading cow data: -5
[Wed Nov  9 20:33:52 2022] elastio-snap: error handling read bio: -5
[Wed Nov  9 20:33:52 2022] elastio-snap: error handling read bio in kernel thread: -5
[Wed Nov  9 20:33:52 2022] elastio-snap: error detected in cow thread, cleaning up cow
[Wed Nov  9 20:33:52 2022] Buffer I/O error on dev elastio-snap0, logical block 220636, async page read


```
And it continue read a lot of blocks after fail. Looks like it reads until get blocks from cow file.

But on branch **feat/allow-memory-mapping** it works as expected:

```
root@user-vm:/home/kgermanov# (sleep 1 && dd if=/dev/urandom of=/tmp/fs/big_file count=100 bs=1M && date)&  dd if=/dev/elastio-snap0 of=/dev/null status=progress && date || date
[1] 279442
159101440 bytes (159 MB, 152 MiB) copied, 2 s, 72.6 MB/s100+0 records in
100+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 1.18215 s, 88.7 MB/s
Wed 09 Nov 2022 08:04:05 PM +04
159233024 bytes (159 MB, 152 MiB) copied, 5 s, 32.5 MB/s
dd: error reading '/dev/elastio-snap0': Input/output error
311264+0 records in
311264+0 records out
159367168 bytes (159 MB, 152 MiB) copied, 4.95383 s, 32.2 MB/s
[1]+  Done                    ( sleep 1 && dd if=/dev/urandom of=/tmp/fs/big_file count=100 bs=1M && date )
Wed 09 Nov 2022 08:04:08 PM +04

root@user-vm:/home/kgermanov# dmesg -T
[Wed Nov  9 20:04:08 2022] elastio-snap: cow file '/tmp/fs/.eliosnap' max size exceeded (10485760/10485760): -27
[Wed Nov  9 20:04:08 2022] elastio-snap: error writing cow data: -27
[Wed Nov  9 20:04:08 2022] elastio-snap: error writing cow data and mapping: -27
[Wed Nov  9 20:04:08 2022] elastio-snap: error handling write bio: -27
[Wed Nov  9 20:04:08 2022] elastio-snap: error handling write bio in kernel thread: -27
[Wed Nov  9 20:04:08 2022] elastio-snap: error detected in cow thread, cleaning up cow
[Wed Nov  9 20:04:08 2022] Buffer I/O error on dev elastio-snap0, logical block 38908, async page read

```

Difference in handle errors. Before there are 3 type of errors and looks like they did not correctly check in all places.
After collapsed to one error state it works good. Created PR for this.

**Comment by kgermanov** [comment]
Today I tested this with utility **fio**. And it was crash. So unfortunatle option is needs.
```
root@user-vm:/home/kgermanov#  fio --readonly --ioengine=mmap  --numjobs=4 --name test --filename=/dev/elastio-snap0
test: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=mmap, iodepth=1
...
fio-3.16
Starting 4 processes
fio: pid=40710, got signal=7
fio: pid=40708, got signal=7
fio: pid=40709, got signal=7
fio: pid=40711, got signal=7
```

Without mmap:
```
root@user-vm:/home/kgermanov/work/agent/bdsnap#  fio --readonly   --numjobs=4 --name test --filename=/dev/elastio-snap0
test: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
...
fio-3.16
Starting 4 processes
fio: io_u error on file /dev/elastio-snap0: Input/output error: read offset=0, buflen=4096
fio: pid=40723, err=5/file:io_u.c:1787, func=io_u error, error=Input/output error
fio: io_u error on file /dev/elastio-snap0: Input/output error: read offset=0, buflen=4096
fio: io_u error on file /dev/elastio-snap0: Input/output error: read offset=0, buflen=4096
fio: pid=40725, err=5/file:io_u.c:1787, func=io_u error, error=Input/output error
fio: pid=40722, err=5/file:io_u.c:1787, func=io_u error, error=Input/output error
fio: io_u error on file /dev/elastio-snap0: Input/output error: read offset=0, buflen=4096
fio: pid=40724, err=5/file:io_u.c:1787, func=io_u error, error=Input/output error

```

**Comment by kgermanov** [comment]
Create PR to draft: https://github.com/elastio/elastio-snap/pull/196
