### ISSUE TITLE
Functionality of CoW file on other device (redirected storge) should be covered with the untit-tests

### ISSUE THREAD

**Issue by e-kov** [elastio/elastio-snap#197]
The functionality to allow placement of the CoW file to some other not a traced  device was implemented #109 and then it was fixed #190. But it is not covered by [unit-tests](https://github.com/elastio/elastio-snap/tree/master/tests).
There are some ideas for possible testing in this area:
https://github.com/elastio/elastio-snap/pull/190#issuecomment-1318551281
https://github.com/elastio/elastio-snap/pull/190#issuecomment-1318574112

**Comment by kgermanov** [comment]
@e-kov. 
1. About EBUSY error. It appears when we try umount target volume. What should we do in such case? There are possible:
2.

**Comment by kgermanov** [comment]
@e-kov  There is same PR for Datto: https://github.com/datto/dattobd/pull/273

**Comment by kgermanov** [comment]
@e-kov About cow_path. For redirected storage we should use absolute path for reload. In another case we cannot find COW file.

**Comment by kgermanov** [comment]
@e-kov Any news?

**Comment by e-kov** [comment]
> @e-kov. About EBUSY error. It appears when we try umount target volume. What should we do in such case? There are possible:
> 
>     1. Allow umount and setup snapshot to failed state
> 
>     2. Do not allow umount target until snapshot exists (As now - https://github.com/elastio/elastio-snap/pull/198/files#diff-4d875dfdaf6bb6d4d40c3e7c0d32a79fd43c025e27bbcaf445bba6fcf48a4ff0R294)

@kgermanov what do you mean as "target" in the 2nd scenario? I assume it's about the 2nd volume which hosts CoW file in this case. I think 2nd option is better. However I do not imagine all possible use-cases right now.

> @e-kov  There is same PR for Datto: https://github.com/datto/dattobd/pull/273. May be needs "port" them changes to elastio?

@kgermanov for some reason they didn't mere this PR into `master`. I have no idea why.

> @e-kov Any news?

No news at all. Thanks for your PR https://github.com/elastio/elastio-snap/pull/198 
I think it will be landed soon.
