### ISSUE TITLE
`test_reload_verified_snapshot` is failing on 3rd kernels and LVM

### ISSUE THREAD

**Issue by e-kov** [elastio/elastio-snap#202]
Maybe it's not a big deal. It's hard to say now. Why? Because this issue happens just on the old 3rd kernels on envs with LVM.
So it happens just on Debian 8 (EOLed) and CentOS 7.

Logs:
[centos7_dmesg.log](https://github.com/elastio/elastio-snap/files/10198668/centos7_dmesg.log)
[centos7_LVM_qcow2.log](https://github.com/elastio/elastio-snap/files/10198669/centos7_LVM_qcow2.log)
[deb8_dmesg.log](https://github.com/elastio/elastio-snap/files/10198671/deb8_dmesg.log)
[deb8_LVM_loop.log](https://github.com/elastio/elastio-snap/files/10198672/deb8_LVM_loop.log)

Appropriate failed build https://github.com/elastio/elastio-snap/actions/runs/3658755251/jobs/6183931747

**Comment by anelson** [comment]
@e-kov what's the support status of RHEL/CentOS 7?  AFAIK it's not EOL yet.

**Comment by e-kov** [comment]
@anelson CentOS 7 EOL date us 2024-06-30
