### ISSUE TITLE
Support Linux kernel 6.1 as on AL2023

### ISSUE THREAD

**Issue by e-kov** [elastio/elastio-snap#239]
Our kernel module should be compilable and should work on AL2023 with Linux kernel 6.1.
Also builds should be added and packages should be provided for this distro.

**Comment by i-krasnoshchokov** [comment]
Retested on version `d3afec9e5dc70b551207d7432272bcd55a37b9d2`

Retesting result: accepted. On the EC2 instance with Amazon Linux 2023 `elastio-snap` was installed successfully 
![image](https://user-images.githubusercontent.com/58442921/232837296-67cb5f39-5452-4905-9789-4c434d876aad.png)

[Tests](https://github.com/elastio/elastio-snap/actions/runs/4702079847/jobs/8340223972) are also running successfully.
