### ISSUE TITLE
Create cow file precisely according to the user setting

### ISSUE THREAD

**Issue by skypodolsky** [elastio/elastio-snap#253]
Now, the size of the COW file is the sum of the header size, mapping section, and the snapshot data itself. This was added in one of the previous tasks and caused some issues with yozhik-tests. This approach implicitly adds some additional size to the `fallocate` specified by the user. After a short discussion we agreed that for the system administrator, it is more critical to precisely control the used disk space used, so we will bring the initial behavior back. This means, that if the user specifies 10% of the disk for the COW file, this should be the precise size of the COW file and no additional data should be added to it.

**Comment by e-kov** [comment]
Also this task includes test for the CoW file size and `fallocate` space size checks.
