### ISSUE TITLE
Failed to destroy snapshot immediately after taking it

### ISSUE THREAD

**Issue by olesiastorchak** [elastio/elastio-snap#26]
Spinof of https://github.com/elastio/assurio/pull/201 issue in assurio repository.
If we run this script with commands for driver cli

```
aioctl setup-snapshot /dev/sda4 "/home/cow0.bin" 0
aioctl destroy 0
```
 it fails with 
```
from /var/log/syslog:
May 15 10:39:31 osboxes kernel: [ 2556.577899] assurio-snap: device specified is busy: -16
May 15 10:39:31 osboxes kernel: [ 2556.577904] assurio-snap: error during destroy ioctl handler: -16
```
I did it for 270 Gb volume.

**Comment by JusSergey** [comment]
@e-kov I think I faced with the same root issue but in my case, it reproduces in a bit another way - in my case, I try to destroy the snapshot immediately after I closed the file-handle and I see the same error. I think the root issue is the same

**Comment by e-kov** [comment]
@JusSergey great, thanks for the confirmation!
Could you please provide some details like volume size, what activity happens between a snapshot creation and deletion, etc.
And, as far as I understood from Olesia's words, in  your case Elastio CLI does snapshot create and then transition to incremental operations under the hood. And the second operation leads to the `device specified is busy: -16` error.
It would be great if you can do `sudo rmmod elatio_snap` and then `sudo modprobe elastio_snap debug=1`, repeat steps and then get dmesg output with the more detailed elastio-snap logs. It's fine even if you already have retries around libelastio-snap calls.
