### ISSUE TITLE
Snapshot reload doesn't work on AWS EC2

### ISSUE THREAD

**Issue by skypodolsky** [elastio/elastio-snap#297]
It was reported by @i-krasnoshchokov that the reload functionality doesn't work on the Debian 12 AWS EC2 instance. This issue has been confirmed and its root cause seems to be irrelevant to what was fixed previously.

**Comment by i-krasnoshchokov** [comment]
Retested on latest elastio-snap `a7ac96f` on Amazon EC2 instance with Debian on it.

Retesting result: accepted. Drivers state and snapshot state are the same after reboot.
`cat /proc/elastio-snap-info` after reboot:
```
admin@ip-172-31-19-121:~$ cat /proc/elastio-snap-info
{
        "version": "0.12.2",
        "devices": [
                {
                        "minor": 0,
                        "cow_file": "/cow0",
                        "block_device": "/dev/nvme0n1p1",
                        "max_cache": 314572800,
                        "fallocate": 1167695872,
                        "seq_id": 1,
                        "uuid": "5da138299dbf484e9a754f183aa7e57d",
                        "version": 1,
                        "nr_changed_blocks": 1993,
                        "state": 3,
                        "ignore_errors": 0,
                        "cow_on_bdev": true
                }
        ]
}
```

Also, after reboot, transition from incremental to snapshot also works correctly.
