### ISSUE TITLE
Excessively large amount of writes causes error writing to COW file

### ISSUE THREAD

**Issue by olesiastorchak** [elastio/elastio-snap#39]
**NOTE FROM @anelson**: This behavior is a consequence of the way the driver is implemented.  I hesitate to even call it a "bug", it's a limitation of the design.

Leaving this open since it does in fact describe the current behavior of the driver, although fixing it would require a substantial change to how we track changes.

---

Original bug in elastio repo - https://github.com/elastio/elastio/issues/474.
Run in debian10 Vagrant build box. 
Steps to repro (with driver's CLI): 
1. create snapshot (sudo elioctl setup-snapshot /dev/vda1 /.elastio/cow0.bin 0)
2. copy driver's metadata file to temp location sudo cp /.elastio/cow0.bin /tmp/cow05.bin
3. lo and behold: 

**system logs:**
```
elastio@debian10-amd64-build:~$ sudo dmesg --ctime | grep error
[Tue Sep  8 12:01:16 2020] elastio-snap: error writing cow data: -27
[Tue Sep  8 12:01:16 2020] elastio-snap: error writing cow data and mapping: -27
[Tue Sep  8 12:01:16 2020] elastio-snap: error handling write bio: -27
[Tue Sep  8 12:01:16 2020] elastio-snap: error handling write bio in kernel thread: -27
```
**driver's interface file:** 
```
elastio@debian10-amd64-build:~/elastio/target/release$ cat /proc/elastio-snap-info 
{
	"version": "0.10.13",
	"devices": [
		{
			"minor": 0,
			"cow_file": "/.elastio/cow0.bin",
			"block_device": "/dev/vda1",
			"max_cache": 314572800,
			"fallocate": 4508876800,
			"seq_id": 1,
			"uuid": "affe491d129e42aca4677d6a76d67ab1",
			"version": 1,
			"nr_changed_blocks": 1079501,
			"error": -27,
			"state": 3
		}
	]
}
```

**Comment by kgermanov** [comment]
@anelson, Looks like this case is invalid.
If we copy cow file, then we generate changes at least as this cow file. And it will failed on write to same cow file with error -27.

**Comment by anelson** [comment]
@kgermanov I'm sorry I don't understand what about this case is invalid.  The issue description seems to describe exactly the behavior you're describing.  

Is your point that this isn't specific to copying from the COW file, that any file of a similar size would trigger this behavior?

**Comment by kgermanov** [comment]
@anelson Yes, any file of similar size would trigger this behavior

**Comment by anelson** [comment]
That makes sense, I'll modify it accordingly.

**Comment by kgermanov** [comment]
@anelson  But there is expected behavour. When storage is full - snapshot would in failed state by design.

**Comment by anelson** [comment]
Yes I agree.  It's a consequence of the way change tracking is implemented.

**Comment by e-kov** [comment]
@kgermanov @anelson thanks for your attention to this issue.
It looks like not a bug, but "as designed" behaviour. And I was going to re-test it an close.

But @anelson I just checked it with `elastio` CLI (not to be confused with `elioctl`) and found unexpected result.
The expected was an error at the `elastio block backup` about exceeded CoW file when cow file was copied to the same device during the backup operation. Instead of that it fails with another really unexpected error.
dmesg:
```
[Nov17 13:59] elastio_snap: loading out-of-tree module taints kernel.
[Nov17 14:02] elastio-snap: physical memory usage has exceeded 80% threshold. cow file update is stopped
[Nov17 14:03] elastio-snap: device specified is in the fail state: -12
[  +0.000019] elastio-snap: error during transition to incremental ioctl handler: -12
```
CLI output, version 1:
```
elastio@debian11-amd64-build:~$ sudo -E elastio block backup /dev/vda1
Backing up 1 block device(s) to default vault using fixed shard
▪ Total                    [00:00:37] >----------------------------------------------------------- 512.00MB/199.04GB Failed
▪   /dev/vda1              [00:00:37] >----------------------------------------------------------- 512.00MB/199.04GB Failed
One or more items failed to ingest:
/dev/vda1: Kolobok error

Caused by:
   0: Volk error
   1: Snapshot: error taking snapshot of [/dev/vda1]
   2: Snapshot /dev/elastio-snap0 for volume /dev/vda1 is in invalid state: 12 (Cannot allocate memory)

Location:
    /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/convert/mod.rs:550:9

Location:
    /home/elastio/elastio/cli/volk/src/job.rs:260:69
Ingest operation has failed: Ingest job has failed

Location:
    /home/elastio/.cargo/registry/src/dl.cloudsmith.io-2dc4edbccd98c64c/cheburashka-4.4.5/src/logging/mod.rs:595:18

```
CLI output, version 2:
```
elastio@debian11-amd64-build:~$ sudo -E elastio block backup /dev/vda1
Backing up 1 block device(s) to default vault using fixed shard
▪ Total                    [00:01:41] >----------------------------------------------------------- 187.06MB/199.04GB Failed
▪   /dev/vda1              [00:01:41] >----------------------------------------------------------- 187.06MB/199.04GB Failed
One or more items failed to ingest:
/dev/vda1: Kolobok error

Caused by:
    Snapshot checker reported unexpected error: -12, see dmesg for more information

Location:
    /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/convert/mod.rs:550:9

Location:
    /home/elastio/elastio/cli/volk/src/job.rs:260:69
Ingest operation has failed: Ingest job has failed

Location:
    /home/elastio/.cargo/registry/src/dl.cloudsmith.io-2dc4edbccd98c64c/cheburashka-4.4.5/src/logging/mod.rs:595:18
```
It's unexpected because of the recent fix of #96 
I'll discuss it with @skypodolsky. And for now let's keep this issue opened to track the new problem.

**Comment by anelson** [comment]
@skypodolsky is the error that Zheka described specifically because he copied the COW file?  If instead he had read the same number of bytes from `/dev/zero` and written that to a file, would the result have been different?

It makes sense to try to prevent users from tampering with the COW file, but the incorrect behavior Zheka described above seems like it's due to the amount of writes in general, without regard to where they came from.  Do you agree?

**Comment by anelson** [comment]
Okay then, that makes sense.

**Comment by i-krasnoshchokov** [comment]
Retested on two versions: `2888d7a857ccf307d67e7a1e1c2d6be6dd8d2888` and `b42b83074fc79a1ab15f2c725192b4581a7edc7e `

Retesting result: accepted. Cow file can't be deleted or moved to other directories:

```
ubuntu@ip-172-31-12-125:~/dir4$ ls -l
total 827580
lrwxrwxrwx   1 root root         7 Dec  1 21:32 bin -> usr/bin
drwxr-xr-x   4 root root      4096 Jan  3 18:36 boot
----------   1 root root 847352576 Jan  5 08:13 cow0
drwxr-xr-x   5 root root      4096 Dec  1 21:34 dev
drwxr-xr-x 100 root root      4096 Jan  5 08:11 etc
drwxr-xr-x   3 root root      4096 Jan  3 18:31 home
lrwxrwxrwx   1 root root         7 Dec  1 21:32 lib -> usr/lib
lrwxrwxrwx   1 root root         9 Dec  1 21:32 lib32 -> usr/lib32
lrwxrwxrwx   1 root root         9 Dec  1 21:32 lib64 -> usr/lib64
lrwxrwxrwx   1 root root        10 Dec  1 21:32 libx32 -> usr/libx32
drwx------   2 root root     16384 Dec  1 21:35 lost+found
drwxr-xr-x   2 root root      4096 Dec  1 21:32 media
drwxr-xr-x   2 root root      4096 Dec  1 21:32 mnt
drwxr-xr-x   2 root root      4096 Dec  1 21:32 opt
drwxr-xr-x   2 root root      4096 Apr 15  2020 proc
drwx------   5 root root      4096 Jan  3 18:36 root
drwxr-xr-x   5 root root      4096 Dec  1 21:38 run
lrwxrwxrwx   1 root root         8 Dec  1 21:32 sbin -> usr/sbin
drwxr-xr-x   8 root root      4096 Dec  1 21:37 snap
drwxr-xr-x   2 root root      4096 Dec  1 21:32 srv
drwxr-xr-x   2 root root      4096 Apr 15  2020 sys
drwxrwxrwt  13 root root      4096 Jan  5 08:11 tmp
drwxr-xr-x  14 root root      4096 Dec  1 21:33 usr
drwxr-xr-x  13 root root      4096 Dec  1 21:35 var

ubuntu@ip-172-31-12-125:~/dir4$ sudo mv cow0 ~/testdir
mv: cannot remove 'cow0': Operation not permitted
ubuntu@ip-172-31-12-125:~/dir4$ sudo rm cow0
rm: cannot remove 'cow0': Operation not permitted
```
