### ISSUE TITLE
Driver stucks when thawing superblock on Debian 11 with the kernel 5.10.0-8-amd64

### ISSUE THREAD

**Issue by e-kov** [elastio/elastio-snap#83]
[dmesg](https://github.com/elastio/elastio-snap/files/7007865/Debian11.log)

**Comment by anelson** [comment]
@e-kov this sounds like a bug for you to deal with.  Feel free to reassign as needed.

**Comment by e-kov** [comment]
The dmesg output here is the same as was on centos8 with the 4.16.0-305 kernel. So this is good issue for @alexxxsereda
