### ISSUE TITLE
Will the system memory be used exhaust?

### ISSUE THREAD

**Issue by zhanghaiyang9999** [elastio/elastio-snap#90]
After creating the snapshot, if the original volume data changes very frequently, will the system memory be exhausted?
Because when one bio comes, need to clone one bio and add the bio to the queue via bio_queue_add.

If the cow file writing is slower than the original volume writing speed, the system memory must be used exhaust and cause system crash, right?

**Comment by anelson** [comment]
@e-kov is working on this very issue now.  We're tracking it under issue #96.  I'm closing this issue in favor of that one.
