### ISSUE TITLE
Investigate the possibility of redirecting cow file into another disk

### ISSUE THREAD

**Issue by Apostoln** [elastio/elastio-snap#91]
The snapshot taking is failed if there is no free space for the `.cow` file. We have a requirement to have `.cow` file on the device for which we are taking a snapshot. Is it possible to place and use the `.cow` file on another device? It would be useful in case where there is no free space left on the device.

This functionality was requested here:
https://elastio.slack.com/archives/C01KP7YSG13/p1633876963237800

cc @e-kov

**Comment by alexxxsereda** [comment]
Investigated and implemented in [108](https://github.com/elastio/elastio-snap/issues/108)
