### ISSUE TITLE
Memory overflow during intensive read/write operations

### ISSUE THREAD

**Issue by alexxxsereda** [elastio/elastio-snap#96]
This issue was observed by working on [3592](https://github.com/elastio/elastio/issues/3592) and reproduced without cli usage, but just running the [stress_copy](https://github.com/elastio/elastio-snap/files/7640259/stress_copy.zip) script.

**Comment by nickchen-cpu** [comment]
I have some ideas if your elastio-snap's user space's reader is using `sequential read` :

1. Don't COW any block whose block number is smaller than the sequential read cursor's `offset`.

**Comment by anelson** [comment]
@e-kov what's the disposition of this issue?  Is it still outstanding?

**Comment by e-kov** [comment]
@anelson yes, I did reproduce this issue a week ago. Now it doesn't lead to the kernel panic, but leads to the snapshot device in the failed state and base image on the next backup.
It's in our queue after #149 and #157
